name: CI

on:
  push:
    branches:
      - main 

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install
      - name: Start server
        run: npm start &

      - name: Run unit tests
        run: npm run test:unit

      - name: Display SoftUni username
        run: echo "Doan1"
  ui-tests:
    runs-on: ubuntu-latest
    needs: build_and_test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install
      - name: Start server
        run: npm start &
      - name: Install playwright browsers
        run: npx playwright install
      - name: Run UI tests
        run: npm run test:ui

      